services:
    server:
        image: server-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4200:4200"
        deploy:
            replicas: 1  # Only one instance of Angular + Express
            restart_policy:
                condition: on-failure
        networks:
            - app_network
        volumes:
            - uploads:/app/uploads
    worker:
        image: worker-app
        build:
            context: .
            dockerfile: src/workers/converter/Dockerfile
        deploy:
            replicas: 5  # 5 worker instances
            restart_policy:
                condition: on-failure
        networks:
            - app_network
        volumes:
            - uploads:/app/uploads

networks:
    app_network:
volumes:
    uploads:
