services:
    # RabbitMQ service
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"  # RabbitMQ communication port
            - "15672:15672" # RabbitMQ management UI (accessible in the browser)
        networks:
            - app_network
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

    # Redis service
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - app_network
        volumes:
            - redis_data:/data
    server:
        image: server-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4200:4200"
        deploy:
            replicas: 1  # Only one instance of Angular + Express
            restart_policy:
                condition: on-failure
        networks:
            - app_network
        volumes:
            - uploads:/app/uploads
        environment:
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
            - REDIS_URL=redis://redis:6379
    worker:
        image: worker-app
        build:
            context: .
            dockerfile: src/workers/converter/Dockerfile
        deploy:
            replicas: 5  # 5 worker instances
            restart_policy:
                condition: on-failure
        networks:
            - app_network
        volumes:
            - uploads:/app/uploads
        environment:
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
            - REDIS_URL=redis://redis:6379
    
networks:
    app_network:
volumes:
    uploads:
    rabbitmq_data:
    redis_data:
